[package]
name = "hs-pack"
version = "0.2.0"
edition = "2021"
description = "Turn any crate into an Haskell library"
repository = "https://github.com/yvan-sraka/hs-pack"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
displaydoc = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
thiserror = "1.0"